on: workflow_dispatch

name: Release

jobs:
  build:
    name: Build and release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: papeloto/action-zip@v1
        with:
          files: target/${{ matrix.target }}/release/vssh
          dest: target/${{ matrix.target }}.zip
      - name: Cache build artifacts for release
        uses: actions/cache@v2
        env:
          cache-name: cache-build-artifacts
        with:
          path: target/*.zip
          key: cache-build-artifacts
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restore build artifacts from cache
        uses: actions/cache@v2
        env:
          cache-name: cache-build-artifacts
        with:
          path: target/
          key: cache-build-artifacts
      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            aarch64-unknown-linux-gnu.zip
            x86_64-apple-darwin.zip
            x86_64-pc-windows-msvc.zip
            x86_64-unknown-linux-gnu.zip